pipelines:
  branches:
    main:
      - step:
          name: Step master pertama
          trigger: automatic
          image: atlassian/default-image
          script:
            - echo "Step pertama"
      - step:
          name: Step master kedua
          trigger: automatic
          image: atlassian/default-image
          script:
            - echo "Step 2"