pipelines:
  branches:
    main:
      - step:
          name: Step master pertama
          image: atlassian/default-image:latest
          script:
            - echo "Step pertama"
      - step:
          name: Step master kedua
          image: atlassian/default-image:latest
          script:
            - echo "Step kedua"
